name: Deploy Backend (ContainerLoad.org)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run deploy.sh in dry-run mode? (true/false)'
        required: false
        default: 'true'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Write known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Run remote deploy script
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DEPLOY_SCRIPT: ${{ secrets.REMOTE_DEPLOY_SCRIPT }}
        run: |
          DRY_RUN=${{ github.event.inputs.dry_run || 'true' }}
          echo "Triggering remote deploy: DRY_RUN=${DRY_RUN}"
          ssh -o UserKnownHostsFile=~/.ssh/known_hosts -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            export CI=true
            export DRY_RUN=${DRY_RUN}
            bash -lc '${REMOTE_DEPLOY_SCRIPT} ${EXTRA_ARGS:-}'
          "
